// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package service2

import "tg-example/contracts/types"

type requestService2Set struct {
	Req types.BaseRequest `json:"req"`
}

type responseService2Set struct {
	Resp *types.BaseResponse `json:"resp"`
}
