// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package example

import "tg-example/contracts/types"

type requestExampleServiceGet struct {
	Req types.BaseRequest `json:"req"`
}

type responseExampleServiceGet struct {
	Resp *types.BaseResponse `json:"resp"`
}
