// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package service1

import (
	"context"
	"fmt"
	"tg-example/contracts/types"
	"tg-example/pkg/clients/service1/jsonrpc"
)

type ClientService1 struct {
	*ClientJsonRPC
}

type retService1Get = func(resp *types.BaseResponse, err error)

func (cli *ClientService1) Get(ctx context.Context, req types.BaseRequest) (resp *types.BaseResponse, err error) {

	request := requestService1Get{Req: req}
	var response responseService1Get
	var rpcResponse *jsonrpc.ResponseRPC
	if rpcResponse, err = cli.rpc.Call(ctx, "service1.get", request); err != nil || rpcResponse == nil {
		return
	}
	if rpcResponse.Error != nil {
		if cli.errorDecoder != nil {
			err = cli.errorDecoder(rpcResponse.Error.Raw())
		} else {
			err = fmt.Errorf(rpcResponse.Error.Message)
		}
		return
	}
	if err = rpcResponse.GetObject(&response); err != nil {
		return
	}
	return response.Resp, err
}

func (cli *ClientService1) ReqGet(ctx context.Context, callback retService1Get, req types.BaseRequest) (request RequestRPC) {

	request = RequestRPC{rpcRequest: &jsonrpc.RequestRPC{
		ID:      jsonrpc.NewID(),
		JSONRPC: jsonrpc.Version,
		Method:  "service1.get",
		Params:  requestService1Get{Req: req},
	}}
	if callback != nil {
		var response responseService1Get
		request.retHandler = func(err error, rpcResponse *jsonrpc.ResponseRPC) {
			if err == nil && rpcResponse != nil {
				if rpcResponse.Error != nil {
					if cli.errorDecoder != nil {
						err = cli.errorDecoder(rpcResponse.Error.Raw())
					} else {
						err = fmt.Errorf(rpcResponse.Error.Message)
					}
				} else {
					err = rpcResponse.GetObject(&response)
				}
			}
			callback(response.Resp, err)
		}
	}
	return
}
