// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package service2

import (
	"context"
	"fmt"
	"tg-example/contracts"
	"tg-example/contracts/types"

	otel "go.opentelemetry.io/otel"
	trace "go.opentelemetry.io/otel/trace"
)

type traceService2 struct {
	next contracts.Service2
}

func traceMiddlewareService2(next contracts.Service2) contracts.Service2 {
	return &traceService2{next: next}
}

func (svc traceService2) Set(ctx context.Context, req types.BaseRequest) (resp *types.BaseResponse, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "service2.set")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Set(ctx, req)
}
