// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package service2

import (
	"context"
	"strconv"
	"tg-example/contracts"
	"tg-example/contracts/types"
	"time"
)

type metricsService2 struct {
	next contracts.Service2
}

func metricsMiddlewareService2(next contracts.Service2) contracts.Service2 {
	return &metricsService2{next: next}
}

func (m metricsService2) Set(ctx context.Context, req types.BaseRequest) (resp *types.BaseResponse, err error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = internalError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("service2", "set", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("service2", "set", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("service2", "set", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.Set(ctx, req)
}
