// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package service2

import (
	"context"
	"tg-example/contracts"
	"tg-example/contracts/types"
	"tg-example/internal/transport/service2/viewer"
	"time"

	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type loggerService2 struct {
	next contracts.Service2
}

func loggerMiddlewareService2() MiddlewareService2 {
	return func(next contracts.Service2) contracts.Service2 {
		return &loggerService2{next: next}
	}
}

func (m loggerService2) Set(ctx context.Context, req types.BaseRequest) (resp *types.BaseResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Service2").Str("method", "set").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "service2.set",
				"request":  viewer.Sprintf("%+v", requestService2Set{Req: req}),
				"response": viewer.Sprintf("%+v", responseService2Set{Resp: resp}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call set")
			return
		}
		logger.Info().Func(logHandle).Msg("call set")
	}(time.Now())
	return m.next.Set(ctx, req)
}
