// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package service2

import (
	"context"
	"tg-example/contracts"
	"tg-example/contracts/types"
)

type Service2Set func(ctx context.Context, req types.BaseRequest) (resp *types.BaseResponse, err error)

type MiddlewareService2 func(next contracts.Service2) contracts.Service2

type MiddlewareService2Set func(next Service2Set) Service2Set
