// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"tg-example/contracts"
	"tg-example/contracts/types"
)

type ExampleServiceGet func(ctx context.Context, req types.BaseRequest) (resp *types.BaseResponse, err error)

type MiddlewareExampleService func(next contracts.ExampleService) contracts.ExampleService

type MiddlewareExampleServiceGet func(next ExampleServiceGet) ExampleServiceGet
