// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"tg-example/contracts"
	"tg-example/contracts/types"
	"tg-example/internal/transport/viewer"
	"time"

	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type loggerExampleService struct {
	next contracts.ExampleService
}

func loggerMiddlewareExampleService() MiddlewareExampleService {
	return func(next contracts.ExampleService) contracts.ExampleService {
		return &loggerExampleService{next: next}
	}
}

func (m loggerExampleService) Get(ctx context.Context, req types.BaseRequest) (resp *types.BaseResponse, err error) {
	logger := log.Ctx(ctx).With().Str("service", "ExampleService").Str("method", "get").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "exampleService.get",
				"request":  viewer.Sprintf("%+v", requestExampleServiceGet{Req: req}),
				"response": viewer.Sprintf("%+v", responseExampleServiceGet{Resp: resp}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call get")
			return
		}
		logger.Info().Func(logHandle).Msg("call get")
	}(time.Now())
	return m.next.Get(ctx, req)
}
