// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"strconv"
	"tg-example/contracts"
	"tg-example/contracts/types"
	"time"
)

type metricsExampleService struct {
	next contracts.ExampleService
}

func metricsMiddlewareExampleService(next contracts.ExampleService) contracts.ExampleService {
	return &metricsExampleService{next: next}
}

func (m metricsExampleService) Get(ctx context.Context, req types.BaseRequest) (resp *types.BaseResponse, err error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = internalError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("exampleService", "get", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("exampleService", "get", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("exampleService", "get", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.Get(ctx, req)
}
