// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package service1

import (
	"context"
	"fmt"
	"tg-example/contracts"
	"tg-example/contracts/types"

	otel "go.opentelemetry.io/otel"
	trace "go.opentelemetry.io/otel/trace"
)

type traceService1 struct {
	next contracts.Service1
}

func traceMiddlewareService1(next contracts.Service1) contracts.Service1 {
	return &traceService1{next: next}
}

func (svc traceService1) Get(ctx context.Context, req types.BaseRequest) (resp *types.BaseResponse, err error) {

	var span trace.Span
	ctx, span = otel.Tracer(fmt.Sprintf("tg:%s", VersionTg)).Start(ctx, "service1.get")
	defer func() {
		span.RecordError(err)
		span.End()
	}()
	return svc.next.Get(ctx, req)
}
