// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package service1

import "tg-example/contracts/types"

type requestService1Get struct {
	Req types.BaseRequest `json:"req"`
}

type responseService1Get struct {
	Resp *types.BaseResponse `json:"resp"`
}
