// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package service1

import (
	"context"
	"tg-example/contracts"
	"tg-example/contracts/types"
)

type Service1Get func(ctx context.Context, req types.BaseRequest) (resp *types.BaseResponse, err error)

type MiddlewareService1 func(next contracts.Service1) contracts.Service1

type MiddlewareService1Get func(next Service1Get) Service1Get
